version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - "9200:9200" #http
      - "9300:9300" #tcp
    environment:
      - discovery.type=single-node